name: npm packager build

on:
  release:
    types: [published]
jobs:
  build-npm-packager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://www.npmjs.com
          scope: '@belicusbr'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
